version: '3.4'

services:
  quizlet:
    image: quizlet
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DEV_PLATFORM: DOCKER
    env_file:
      - .env
    ports:
      - 3333:3333
    volumes:
      - ./:/app
